spring:
  application:
    name: batch
  datasource:
    url: jdbc:postgresql://localhost:5432/ord # PostgreSQL
    username: batch
    password: "!Q2w3e4r5t"
    hikari:
      maximum-pool-size: 120
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false # Disable Spring Boot default JobRunner
      name: combat0002
    jdbc:
      initialize-schema: always # Initialize Spring Batch meta data tabaes

app: # Handle in NovaBatchProperties component
  chunk-size: 10000 # 청크당 처리 단위 개수 (Spring Batch chunk size)
  use-partitioner: false # true: 파티셔닝(멀티 쓰레드) 활성화, false: 단일 스레드 실행
  grid-size: 100 # 파티션 수 (= 병렬 처리 스레드 수)
  use-virtual-thread: false # true: Virtual Thread 사용, false: 일반 ThreadPoolExecutor 사용
  normal-thread-pool-min-size: 16 # 일반 ThreadPool 최소 사이즈
  normal-thread-pool-max-size: 24 # 일반 ThreadPool 최대 사이즈
  normal-thread-pool-queue-capacity: 1000 # 일반 ThreadPool 큐 용량