spring:
  application:
    name: batch
  datasource:
    url: jdbc:postgresql://localhost:5432/ord # PostgreSQL
    username: batch
    password: "!Q2w3e4r5t"
    hikari:
      maximum-pool-size: 120
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false # Disable Spring Boot default JobRunner
      name: combat0001
    jdbc:
      initialize-schema: always # Initialize Spring Batch meta data tabaes

app: # Handle in NovaBatchProperties component